 enum ACTIONS {

SIGNIN_ATTEMPTS =  "SIGN IN ATTEMPTS" ,
RESET_PASSWORD_ATTEMTPS = "RESET_PASSWORD_ATTEMPTS"  ,
CHANGE_PASSWORD_ACTION="CHANGE_PASSWORD_ACTION" ,
RESET_PHONE_NUMBER_ATTEMPTS= "RESET PHONE NUMBER ATTEMPTS" ,
RESET_PHONE_NUMBER_ACCTION ="RESET PHONE NUMBER ACTION" ,

LOGIN_ATTEMPTS ="LOGIN ATTEMPTS" , 
CREATE_POLICY_ATTEMPTS = "CREATE POLICY ATTEMPTS" ,
EDIT_POLICY_ATTEMPTS = "EDIT POLICY ATTEMPTS" ,
CHANGE_PASSWORD_ATTEMPTS =  "CHANGE PASSWORD ATTEMTPS" ,
GET_ALL_CLIENTS_ACTION ="GET ALL CLIENTS ACTION " ,
GET_A_USER_ACTION = "GET A USER ACTION" ,
REQUEST_PERSONAL_LOAN_ATTEMPTS ="REQUEST PERSONAL LOAN ATTEMPTS" ,
APPROVE_LOAN_ACTION ="ACCEPT LOAN ACTION" ,
DENY_LOAN_ACTION ="DENY LOAN ACTION" ,
FETCH_ALL_LOAN_ACTION ="FETCH ALL LOAN" ,
FETCH_USER_LOAN ="FETCH USER LOAN" , 
FETCH_AGENT_LOAN ="FETCH AGENT LOAN" ,
REQUEST_SME_LOAN_ATTEMPTS ="REQUEST SME LOAN" ,
CREATE_USER_ACTION ="CREATE USER ACTION" ,
CREATE_USER_ATTEMPTS ="CREATE USER ATTEMPTS",
USER_LOGIN_ATTEMPTS ="USER LOGIN ATTEMPTS" ,
USER_LOGIN_ACTION="USER LOGIN ACTION"  ,
FETCH_ALL_USERS ="FETCH ALL USERS" ,
BLOCK_A_USER_ATTEMPTS = "BLOCK A USER ATTEMTPS"

 }